spring.application.name=Ai

#spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}

spring.ai.google.genai.api-key=AQ.Ab8RN6JMJa6NJ5Dur9b9Jlu80kxP2XLPc1pAUBHrw7dhstoS7Q

spring.ai.google.genai.chat.options.model=gemini-2.5-flash