name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

       # <<< ADDED
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # <<< ADDED
      - name: Build React App
        working-directory: spring-ai-demo-react
        run: |
          npm install
          npm run build

      # <<< ADDED
      - name: Copy React Build to Spring Boot
        run: |
          mkdir -p src/main/resources/static
          cp -r spring-ai-demo-react/build/* src/main/resources/static/

      - name: Build JAR
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Check Secrets
        run: |
          echo "Username length: ${#DOCKER_USERNAME}"
          echo "Password length: ${#DOCKER_PASSWORD}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop spring-demo || true
            docker rm spring-demo || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest
            docker run -d \
              --name spring-demo \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/spring-boot-ci-demo:latest
